### ISSUE TITLE
Stores initialise as empty array rather than undefined

### ISSUE THREAD

**Issue by mjadobson** [Azarattum/CRStore#6]
```svelte
$posts // --> []
$posts // --> [{},{},{},{}]
```

Because an empty array is a valid output, this can't be relied upon to assess subscription status (initialising, refreshing, loading...). It would be helpful to either initialise as `undefined` or have array status methods (eg: `$posts.loading`)

**Comment by Azarattum** [comment]
Initializing as empty array in intended behavior. It makes cases simpler where you don't have to have a loading state. In the cases where you want a loading state, there is a `ready($posts)` helper that does exactly what you want. 

It is mentioned in the **Setup server side rendering** section in readme. I guess I need to update the docs and make a separate section for this helper since it's a pretty common use case. Thanks for pointing out this out!

**Comment by mjadobson** [comment]
> Initializing as an empty array is an intended behavior. It makes cases simpler where you don't have to have a loading state. In the cases where you want a loading state, there is a `ready($posts)` helper that does exactly what you want.
> 
> It is mentioned in the **Setup server side rendering** section in the readme. I guess I need to update the docs and make a separate section for this helper since it's a pretty common use case. Thanks for pointing this out!

Thanks, I totally missed that!! I'll close the issue.
